[package]
name = "misskey-booru-rs"
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level = 3
codegen-units = 1
panic = "abort"
lto = "fat"
strip = "symbols"

[dependencies]
log = "0.4.27"
nanoserde = "0.2.1"
pretty_env_logger = "0.5.0"
rand = "0.9.1"
ureq = "3.0.11"
